### PR TITLE
Created 2 helpers functions, connecting to database and export dataframe to database

### PR DESCRIPTION
**Pull request by jeffisnotahero**
Created 2 helpers functions, connecting to database and export dataframe to database with snippet in __name__ == “__main__".
Created 1 function, create a small dataframe which to be removed later, to test 2 helpers functions to determine if those work as expected.
Also, practiced pull request.

### CODE REVIEW

**Review by allenjhuang — APPROVED** [review]
Good idea to create helper functions for some of the stuff. We should stay consistent in comments describing our functions, so we should also add similar documentation for some other functions in this file. I think we can do that in another PR though.

**Review by jquach-law — APPROVED** [review]
I am still trying to understand both updates in detail but so far LGTM.

**Comment by Iverefiner** [comment]
lgtm

**Review by Iverefiner — APPROVED** [review]
nice comments

**Pull request merged**
