### PR TITLE
Revert back to 321e6a7

### PR DESCRIPTION
**Pull request by jeffisnotahero**
Revert back to 321e6a7, latest commit that was committed by Allen.

Guys, my apologize. I screwed up my gut pull(somehow reverted excel_cvs_conversion.py when trying to git pull),
then accidentally committed and pull requested it with my latest commit of get_excel_file.py.

Please kindly help check the reverted content. It should be correct.

"$git checkout 321ee6a7 -- excel_cvs_conversion.py"

### CODE REVIEW

**Review by allenjhuang — APPROVED** [review]

**Comment by allenjhuang** [comment]
Hey Jeff, you made this pull request a draft. Was that intentional?

**Comment by allenjhuang** [comment]
It also looks like the Github Action was accidentally removed some time ago. ~~Could you add that back in? We can do that in a separate pull request if you want.~~ Nm, I added it back in with #19.

**Comment by jquach-law** [comment]
Sorry, I am not very good with Git. I have been trying to revert just excel_csv_conversion.py without reverting Jeff's whole commit, but it is trickier than I thought.

This is good tho. thanks, Jeff.

**Review by jquach-law — APPROVED** [review]
Yeah, this looks, I think, exactly the same as before. Awesome

**Comment by jeffisnotahero** [comment]
Hey guys. Thank you so much for the review and approval.
Yes, it is intentional to make this git pull request as draft as I want to ensure that this pull request content is reviewed and correct before being merged.

@jquach-law 
Yea, I used "$git checkout 321ee6a7 -- excel_cvs_conversion.py".

**Pull request merged**
